### ISSUE TITLE
zsysd daemon keeps dying (SIGSEGV) if property canmount of rpool is set to noauto

### ISSUE THREAD

**Issue by lciti** [ubuntu/zsys#194]
**Describe the bug**
At some point zsysctl stopped working (with "ERROR couldn't connect to zsys daemon..."). Running `journalctl -fe` showed that systemd was trying to start the daemon and failing, then retrying etc. The daemon zsysd daemon was failing with an error similar to:
```
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: level=warning msg="Didn't find origin \"rpool/USERDATA/root_yknyg2\" for \"rpool/USERDATA/root_yknyg2@command_line\" matching any dataset"
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x96060a]
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: goroutine 1 [running]:
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/internal/machines.(*Machines).refresh(0xc000380000, 0xbec260, 0xc0000b8020)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/internal/machines/machines.go:227 +0xf0a
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/internal/machines.New(0xbec260, 0xc0000b8020, 0xc000108070, 0x6e, 0xc000129b08, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/internal/machines/machines.go:145 +0x79a
Feb 28 14:55:52 HOSTNAME systemd[1]: Failed to start ZSYS daemon service.
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/internal/daemon.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x68791d, 0xc0000de7e0, 0xbdcc20)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/internal/daemon/daemon.go:115 +0x451
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/cmd/zsysd/daemon.glob..func2(0xff0680, 0x105a4e8, 0x0, 0x0)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/cmd/zsysd/daemon/zsysd.go:30 +0x88
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).execute(0xff0680, 0xc0000a01e0, 0x0, 0x0, 0xff0680, 0xc0000a01e0)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xff0680, 0xb, 0x7fff2d6dcee2, 0x5)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: github.com/ubuntu/zsys/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/vendor/github.com/spf13/cobra/command.go:864
Feb 28 14:55:52 HOSTNAME zsysd[2983805]: main.main()
Feb 28 14:55:52 HOSTNAME zsysd[2983805]:         github.com/ubuntu/zsys/cmd/zsysd/main.go:36 +0xdb
```

After quite some debugging, I tracked down the error to the fact that for some reason I must have set the property `canmount` of `rpool` to `noauto`. Setting the property back to `off` fixes the issue.
I am reporting this issue in case others run into the same problem.
I also wonder if zsysd should handle this problem more gracefully and or give a more informative error message.

**To Reproduce**
The yaml test file below reproduces the error when run in the zsys testing suite (`TestNew` test in `machines_test.go`):
[rpool_canmount_noauto.yaml.txt](https://github.com/ubuntu/zsys/files/6104080/rpool_canmount_noauto.yaml.txt)

**Installed versions:**
 - OS: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Zsysd running version: 0.4.8

**Additional context**

**Comment by lciti** [comment]
I have created a PR #195 with the scripts I used to get to the bottom if this issue. I used these scripts to write a yaml test configuration file corresponding to my physical zfs layout. I verified that the test failed in the same way as the physical layout. I then started to simplify the yaml file gradually while still checking that the test kept failing (this is faster and more convenient than messing up with the actual zfs datasets and snapshots). I could then create a sort of MWE reproducing the error and figured out what the problem was. I hope the code I wrote can be useful to others.

**Comment by didrocks** [comment]
Thanks for looking and digging into it! I’m unsure integrating some LUA script to the repo is a good fit, but maybe we can move that over to the wiki?

Anyway, that will helps us reproducing the problem, thanks for reducing the issue to a simple test case! :)

**Comment by coaxial** [comment]
Thanks, ran into this issue too and setting `canmount` to `on` for my `rpool/USERDATA/root_<id>` fixed it.
