### ISSUE TITLE
unable to start zsysd if there's a ZFS voulme

### ISSUE THREAD

**Issue by jessesung** [ubuntu/zsys#80]
Tested with zsys:amd64 0.4.2 in the Focal archive.

```
systemd[1]: Starting ZSYS daemon service...
zsysd[3596901]: level=warning msg="CanMount property for \"zpool/swap\" has an unexpected source: \"\""
zsysd[3596901]: panic: runtime error: invalid memory address or nil pointer dereference
zsysd[3596901]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x9429d3]
zsysd[3596901]: goroutine 67 [running]:                    
zsysd[3596901]: github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0x0)
zsysd[3596901]: #011github.com/ubuntu/zsys/internal/zfs/zfs.go:134 +0x43
zsysd[3596901]: github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc000800b00)
zsysd[3596901]: #011github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
zsysd[3596901]: github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc0000c8d00)
zsysd[3596901]: #011github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
zsysd[3596901]: github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets.func1(0xc0000c8b00)
zsysd[3596901]: #011github.com/ubuntu/zsys/internal/zfs/zfs.go:135 +0x75
zsysd[3596901]: created by github.com/ubuntu/zsys/internal/zfs.Zfs.Datasets
zsysd[3596901]: #011github.com/ubuntu/zsys/internal/zfs/zfs.go:141 +0xe8
systemd[1]: zsysd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: zsysd.service: Failed with result 'exit-code'. 
systemd[1]: Failed to start ZSYS daemon service.           
systemd[1]: Starting ZSYS daemon service...
```

**Comment by didrocks** [comment]
Thanks for raising this! We discovered a bug in go-libzfs bindings and in our implementation as well. A fix + tests are on the way :)
